### ISSUE TITLE
Hardware solution

### ISSUE THREAD

**Issue by fab4U** [jenskueper/festool-ctl-sys-bluetooth#1]
If one likes to solve the given task in hardware here is a circuit that works without a microcontroller. The relay is a compact reed type and conveniently has a built-in diode.
![BluVac Schaltung](https://user-images.githubusercontent.com/6338485/107747275-77695800-6d17-11eb-829d-80c9faa5eafb.jpg)

The following consideration might be of interest, too. This device will probably be operated for more than 10 years in a rather dusty environment. During the years dust will settle on the pcb. If this layer of dust attracts humidity from the surrounding air it will form a slightly conductive layer giving rise to leak currents from the 230 V supply. This poses a small risk of fire. As a remedy one might want to cover the final pcb with some insulating lacquer (e. g. CRC Plastik 70, two layers). Also make sure that all components have a distance of at least 5 mm to all traces at 230 V.

**Comment by Nosnahc** [comment]
Thank's a lot for your solution!
Is there a place where I can find a PCB routing of this please?

**Comment by fab4U** [comment]
This is only a circuit idea. There is not routing or ready-made pcb available. Sorry!
